CREATE TABLE price (
    id SERIAL PRIMARY KEY,
    product_id VARCHAR NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    "date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_product
      FOREIGN KEY(product_id) 
	  REFERENCES product("id")
)